### ISSUE TITLE
Uncaught error when running Basic.Graphics.And.Fixes.exe, after all files get downloaded

### ISSUE THREAD

**Issue by tstavrianos** [halgari/wabbajack#13]
**Describe the bug**
```
Wabbajack Build - 912ad75bfa891ba84fb156e1a7964c7db0f119f9
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Wabbajack.Installer.HashArchives()
   at Wabbajack.Installer.Install()
   at Wabbajack.AppState.<>c__DisplayClass56_0.<ExecuteBegin>b__1()
Uncaught error:
Object reference not set to an instance of an object.
:<ExecuteBegin>b__1:0:0
:RunInternal:0:0
:Run:0:0
:Run:0:0
:ThreadStart:0:0
```

**Additional context**
Win10 64bit.
Run Basic.Graphics.And.Fixes.exe and set it to check the folder where I have a bunch of files downloaded of nexus. It verified all the files and generated .sha files for them and then produced the above message in the log file and terminated.

**Solution**

**Comment by tstavrianos** [comment]
Nvm, I run it again on a blank folder and it works without issues (apart for luxor's mods where it fails)
